name: Deploy PHP Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Specify your PHP version here

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Sync Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "/var/www/html/laptopdes.com"
          strip_components: 1
          rm: true  # Removes files that are not present in the source

      - name: Final Setup on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 90m
          script: |
            cd /var/www/html/laptopdes.com
            composer install --no-dev
            sudo chown -R www-data:www-data /var/www/html/laptopdes.com
            sudo find /var/www/html/laptopdes.com -type d -exec chmod 755 {} \;
            sudo find /var/www/html/laptopdes.com -type f -exec chmod 644 {} \;
            sudo systemctl restart apache2
