name: Deploy PHP Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Tar Archive Excluding .git and .github
        run: tar --exclude='.git' --exclude='.github' -czf project.tar.gz .

      - name: Upload Tar Archive to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "project.tar.gz"
          target: "/tmp/project.tar.gz"

      - name: Final Setup on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 90m
          script: |
            # Remove all files and directories except wp-config.php
            find /var/www/html/laptopdes.com -mindepth 1 ! -regex '^/var/www/html/laptopdes.com/wp-config\.php$' -delete

            # Extract the tar file
            tar -xzf /tmp/project.tar.gz -C /var/www/html/laptopdes.com

            # Change permissions for WordPress directories
            sudo chown -R www-data:www-data /var/www/html/laptopdes.com
            sudo find /var/www/html/laptopdes.com -type d -exec chmod 755 {} \;
            sudo find /var/www/html/laptopdes.com -type f -exec chmod 644 {} \;

            # Restart web server if needed
            sudo systemctl restart apache2
